name: image_map_builder
description: Image map builder 파트.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  build: '>=2.0.0 <3.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  image_map_core:
    path: ../core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0